export enum WeekDays {
  'SATURDAY' = 'SATURDAY',
  'SUNDAY' = 'SUNDAY',
  'MONDAY' = 'MONDAY',
  'TUESDAY' = 'TUESDAY',
  'WEDNESDAY' = 'WEDNESDAY',
  'THURSDAY' = 'THURSDAY',
  'FRIDAY' = 'FRIDAY',
}
