export enum SystemSettingsEnum {
  'FILE_SIZE_LIMIT_IN_MEGA_BYTE' = 'FILE_SIZE_LIMIT_IN_MEGA_BYTE',
  'FILE_UPLOAD_LIMIT_PER_DAY' = 'FILE_UPLOAD_LIMIT_PER_DAY',
  'AZAN_DURATION' = 'AZAN_DURATION',
}
